//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountMST
    {
        public accountMST()
        {
            this.storeMSTs = new HashSet<storeMST>();
            this.userDetails = new HashSet<userDetail>();
        }
    
        public decimal accountID { get; set; }
        public string accountName { get; set; }
        public string accountCode { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastmodifiedDate { get; set; }
        public Nullable<decimal> LastmodifiedBy { get; set; }
        public string accountManage { get; set; }
        public string accountManageContact { get; set; }
        public Nullable<decimal> allowedStoreNumber { get; set; }
        public Nullable<decimal> allowedUserNumber { get; set; }
    
        public virtual ICollection<storeMST> storeMSTs { get; set; }
        public virtual ICollection<userDetail> userDetails { get; set; }
    }
}
