//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerMST
    {
        public customerMST()
        {
            this.inquiryMSTs = new HashSet<inquiryMST>();
            this.walkinDetails = new HashSet<walkinDetail>();
        }
    
        public decimal customerID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middelName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> aniverssaryDate { get; set; }
        public string homeNumber { get; set; }
        public string cellNumber { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string carNumber { get; set; }
        public string carCompany { get; set; }
        public Nullable<decimal> customerTypeID { get; set; }
        public Nullable<decimal> customerStatusID { get; set; }
        public Nullable<bool> provideNotification { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string companyName { get; set; }
        public string designation { get; set; }
        public string workPhone { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastmodifiedDate { get; set; }
        public Nullable<decimal> LastmodifiedBy { get; set; }
        public string customerPIC { get; set; }
        public string PANNumber { get; set; }
        public string PANCopy { get; set; }
        public string DrivingLicenseNumber { get; set; }
        public string DrivingLicenseCopy { get; set; }
    
        public virtual customerStatusMST customerStatusMST { get; set; }
        public virtual customerTypeMST customerTypeMST { get; set; }
        public virtual ICollection<inquiryMST> inquiryMSTs { get; set; }
        public virtual ICollection<walkinDetail> walkinDetails { get; set; }
    }
}
