//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTypeMST
    {
        public customerTypeMST()
        {
            this.customerMSTs = new HashSet<customerMST>();
        }
    
        public decimal customerTypeID { get; set; }
        public string customerType { get; set; }
        public string typeDetail { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<customerMST> customerMSTs { get; set; }
    }
}
