//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class followup
    {
        public decimal followupID { get; set; }
        public Nullable<System.DateTime> followupDate { get; set; }
        public Nullable<decimal> inquiryID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDone { get; set; }
        public Nullable<System.DateTime> doneDate { get; set; }
        public string followupDetail { get; set; }
        public string followupType { get; set; }
    
        public virtual inquiryMST inquiryMST { get; set; }
    }
}
