//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class inquiryMST
    {
        public inquiryMST()
        {
            this.followups = new HashSet<followup>();
        }
    
        public decimal inquiryMST1 { get; set; }
        public Nullable<decimal> customerID { get; set; }
        public string custName { get; set; }
        public Nullable<decimal> productID { get; set; }
        public string productName { get; set; }
        public string productCode { get; set; }
        public Nullable<decimal> productUnitPrice { get; set; }
        public Nullable<decimal> discountedPrice { get; set; }
        public string inquiryType { get; set; }
        public string inquiryStatus { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<decimal> deletedby { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<decimal> createdBy { get; set; }
        public string inquiryOwner { get; set; }
        public Nullable<decimal> inquiryOwnerID { get; set; }
        public Nullable<System.DateTime> inquiryNextFollowupDate { get; set; }
        public Nullable<decimal> storeID { get; set; }
    
        public virtual customerMST customerMST { get; set; }
        public virtual ICollection<followup> followups { get; set; }
        public virtual productMST productMST { get; set; }
        public virtual storeMST storeMST { get; set; }
        public virtual userDetail userDetail { get; set; }
    }
}
