//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class productMST
    {
        public productMST()
        {
            this.inquiryMSTs = new HashSet<inquiryMST>();
        }
    
        public decimal productID { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string productDesciption { get; set; }
        public Nullable<decimal> categoryID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastmodifiedDate { get; set; }
        public Nullable<decimal> LastmodifiedBy { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string productPic { get; set; }
    
        public virtual categoryMST categoryMST { get; set; }
        public virtual ICollection<inquiryMST> inquiryMSTs { get; set; }
        public virtual userDetail userDetail { get; set; }
        public virtual userDetail userDetail1 { get; set; }
    }
}
