//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesDBEntities1 : DbContext
    {
        public SalesDBEntities1()
            : base("name=SalesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountMST> accountMSTs { get; set; }
        public DbSet<categoryMST> categoryMSTs { get; set; }
        public DbSet<customerMST> customerMSTs { get; set; }
        public DbSet<customerStatusMST> customerStatusMSTs { get; set; }
        public DbSet<customerTypeMST> customerTypeMSTs { get; set; }
        public DbSet<followup> followups { get; set; }
        public DbSet<inquiryMST> inquiryMSTs { get; set; }
        public DbSet<messageMail> messageMails { get; set; }
        public DbSet<productMST> productMSTs { get; set; }
        public DbSet<storeMST> storeMSTs { get; set; }
        public DbSet<userDetail> userDetails { get; set; }
        public DbSet<userGroupMST> userGroupMSTs { get; set; }
        public DbSet<walkinDetail> walkinDetails { get; set; }
    }
}
