//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonyWeb_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetail
    {
        public userDetail()
        {
            this.inquiryMSTs = new HashSet<inquiryMST>();
            this.messageMails = new HashSet<messageMail>();
            this.messageMails1 = new HashSet<messageMail>();
            this.productMSTs = new HashSet<productMST>();
            this.productMSTs1 = new HashSet<productMST>();
            this.walkinDetails = new HashSet<walkinDetail>();
        }
    
        public decimal userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string contactNumber { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string userName { get; set; }
        public string userPass { get; set; }
        public Nullable<decimal> userGroupID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastmodifiedDate { get; set; }
        public Nullable<decimal> LastmodifiedBy { get; set; }
        public Nullable<decimal> accountID { get; set; }
        public Nullable<decimal> storeID { get; set; }
    
        public virtual accountMST accountMST { get; set; }
        public virtual ICollection<inquiryMST> inquiryMSTs { get; set; }
        public virtual ICollection<messageMail> messageMails { get; set; }
        public virtual ICollection<messageMail> messageMails1 { get; set; }
        public virtual ICollection<productMST> productMSTs { get; set; }
        public virtual ICollection<productMST> productMSTs1 { get; set; }
        public virtual storeMST storeMST { get; set; }
        public virtual userGroupMST userGroupMST { get; set; }
        public virtual ICollection<walkinDetail> walkinDetails { get; set; }
    }
}
